BEGIN;

CREATE TABLE IF NOT EXISTS players.footballPlayer
(
    id SERIAL NOT NULL PRIMARY KEY,
    name CHARACTER VARYING(40) NOT NULL,
    surname CHARACTER VARYING(40) NOT NULL,
    gender BOOLEAN NOT NULL,
    birthDate DATE NOT NULL,
    teemName CHARACTER VARYING(40) NOT NULL,
    country CHARACTER VARYING(40) NOT NULL
)

END;